# Generated by Django 4.2.1 on 2023-07-23 23:41

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, unique=True, verbose_name='RG')),
                ('ingresso', models.DateField(verbose_name='Data de ingresso')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumb': (124, 124)}, verbose_name='Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
