# Generated by Django 4.2.1 on 2023-07-24 02:20

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='alunos', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
